### ISSUE TITLE
explore using ChatGPT API

### ISSUE THREAD

**Issue by mongodben** [mongodben/mongodb-oracle#12]
OpenAI recently released the ChatGPT API, which makes it easier to build chatbots. See if can incorporate in the project w successful results.

docs: https://platform.openai.com/docs/guides/chat/introduction

**Comment by nlarew** [comment]
@mongodben we're using this now through the chatgpt lib https://www.npmjs.com/package/chatgpt

**Comment by mongodben** [comment]
per above comment, closing this issue
